spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:lesson_6'
    username: panda
    password: 9779
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 5m